// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfXDLsMvGclb1ia9IcHBqlq5NZAiZ9AKg',
    appId: '1:669507956172:web:3eed91ec28373393fdc169',
    messagingSenderId: '669507956172',
    projectId: 'lost-and-found-e7100',
    authDomain: 'lost-and-found-e7100.firebaseapp.com',
    storageBucket: 'lost-and-found-e7100.firebasestorage.app',
    measurementId: 'G-VXQNPTKRJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuIjZpj2NzyfQrWLQltQ9Jja7R1hC0-NY',
    appId: '1:669507956172:android:865592095c49d127fdc169',
    messagingSenderId: '669507956172',
    projectId: 'lost-and-found-e7100',
    storageBucket: 'lost-and-found-e7100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDQuQPQUmQLlVdvjZU_61I63rNeH1CNm0',
    appId: '1:669507956172:ios:bfa8b338d7f0aa6bfdc169',
    messagingSenderId: '669507956172',
    projectId: 'lost-and-found-e7100',
    storageBucket: 'lost-and-found-e7100.firebasestorage.app',
    iosClientId: '669507956172-mf9q0prh287iqe7e86rc7kr0d7erdk3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostAndFoundBd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDQuQPQUmQLlVdvjZU_61I63rNeH1CNm0',
    appId: '1:669507956172:ios:bfa8b338d7f0aa6bfdc169',
    messagingSenderId: '669507956172',
    projectId: 'lost-and-found-e7100',
    storageBucket: 'lost-and-found-e7100.firebasestorage.app',
    iosClientId: '669507956172-mf9q0prh287iqe7e86rc7kr0d7erdk3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostAndFoundBd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfXDLsMvGclb1ia9IcHBqlq5NZAiZ9AKg',
    appId: '1:669507956172:web:cfb7bd8b8e3ba9bffdc169',
    messagingSenderId: '669507956172',
    projectId: 'lost-and-found-e7100',
    authDomain: 'lost-and-found-e7100.firebaseapp.com',
    storageBucket: 'lost-and-found-e7100.firebasestorage.app',
    measurementId: 'G-JZB0H94Z6Z',
  );


}
